- name: Hello World Sample
  gather_facts: yes
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - shell: ps -eo pcpu,user,args | sort -r -k1 | head -n5
      register: ps
    - debug: var=ps.stdout_lines

